### ISSUE TITLE
Error: (process:117774): GLib-GObject-CRITICAL **: 21:07:43.305: g_object_get_qdata: assertion 'G_IS_OBJECT (object)' failed

### ISSUE THREAD

**Issue by plasticfigurine** [firecat53/networkmanager-dmenu#102]
NetworkManager-Dmenu runs, but I get the following errors:

(process:117774): GLib-GObject-CRITICAL **: 21:07:43.305: g_object_get_qdata: assertion 'G_IS_OBJECT (object)' failed
(process:117774): GLib-GObject-CRITICAL **: 21:07:43.305: g_object_set_qdata_full: assertion 'G_IS_OBJECT (object)' failed
(process:117774): GLib-GObject-CRITICAL **: 21:07:43.305: g_object_set_qdata_full: assertion 'G_IS_OBJECT (object)' failed
(process:117774): GLib-GObject-CRITICAL **: 21:07:43.305: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

This is an install of networkmanager-dmenu-git  r153.da15351 on Arch Linux.

**Comment by firecat53** [comment]
This is a common issue with a lot of Gtk apps. It doesn't affect anything and
you won't even notice once you've bound networkmanager_dmenu to a keyboard
shortcut :) Let me know if you have an idea how to fix. Otherwise, closing. See
also #97.
