### ISSUE TITLE
ValueError: Namespace NM not available

### ISSUE THREAD

**Issue by Amarakon55** [firecat53/networkmanager-dmenu#103]
The distribution I use is Gentoo.

This is the error I get when I try to run it:
`Traceback (most recent call last):
  File "/usr/bin/networkmanager_dmenu", line 25, in <module>
    gi.require_version('NM', '1.0')
  File "/usr/lib/python3.9/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace NM not available`

I saw the same issue and the solution was to install libnm-glib. On Gentoo, libnm-glib is available from an external repository. I added it and tried to install it but it gave me an error. I wasn't able to install libnm-glib. Where else can I install libnm-glib from?

**Comment by firecat53** [comment]
First, make sure you have python3-gobject installed (or whatever the equivalent Gentoo package is). I have zero experience with Gentoo!

If that doesn't work, I'm not sure I can help directly, however I can suggest a workaround using [Toolbox](https://github.com/containers/toolbox). Let me know if you want to try that route.

**Comment by firecat53** [comment]
Did you ever get this resolved?

**Comment by Amarakon55** [comment]
No, I didn't get this resolved. I don't use this program anymore. I will close this issue.

**Comment by hisekai** [comment]
I just wanted to say that I had the same issue and it was solved by installing the following:
gir1.2-nm-1.0
