### ISSUE TITLE
positioning and size of dmenu

### ISSUE THREAD

**Issue by Fuseteam** [firecat53/networkmanager-dmenu#104]
someone submitted [a patch](https://tools.suckless.org/dmenu/patches/xyw/dmenu-xyw-5.0.diff) for dmenu to control both the position ans size of the menu. perhaps a few sane values could be integrated for the case when the user switches to the vertical layout?

**Comment by firecat53** [comment]
All dmenu/rofi configuration is done by adding CLI flags to the `dmenu_command`
option in your config file (see the README) or passing them on the command line.
I recently removed all theming from this code base to reduce complexity and make
it easier to use different menu applications if desired. Closing, but thanks for
the interest!

**Comment by Fuseteam** [comment]
I know that, i was just hoping you'd be interested in making it into an actual menu by default. I wasn't asking to make the sizing/positoning configurable

**Comment by firecat53** [comment]
I guess I'm not sure what you are looking for here, as far as making it an
"actual menu". The dmenu positioning is all done through CLI flags that each
user can set via the config file. I'm guessing most people won't be using that
patch, so it's a non-issue anyways. Also, a fair number of people use Rofi,
which is also configured through the theme files. 

Right now, the only hard-coded configuration for each different launcher (dmenu,
Rofi and bemenu) are the flags for the password input. I'd rather not add any
other launcher-specific code if it can be avoided.

**Comment by Fuseteam** [comment]
the vertical layout is currently a screenwide dropdown with a sane height. with an "actual" menu i mean similar to those indicator menus in DEs.
honestly if you're not interested in supporting this as a feature that's fine too i guess

but i'm not interested in rofi and i'm not interesting in creating a new config file with just a single line with a custom dmenu command. so uh how does that `-l` exception actually work? perhaps i can include additional exceptions on my own fork

**Comment by Fuseteam** [comment]
yay [i finally figured it out](https://github.com/dwnity/networkmanager-dmenu/commit/c1d000ff823ff72c6602a02f495cf42610c1ac7e)~ i guess now  i just need to figure out how to get the length of the longest line or something
