### ISSUE TITLE
WPA3

### ISSUE THREAD

**Issue by saghya** [firecat53/networkmanager-dmenu#112]
`networkmanager_dmenu` only shows security levels up to WPA2

**Comment by firecat53** [comment]
Thanks for pointing that out. Possible fix pushed with the `develop` branch, but I don't have access to a WPA3 connection to test with! Let me know if it shows WPA3 connections correctly and if you can connect to and save a WPA3 connection.  Thanks!

**Comment by saghya** [comment]
Thanks for the quick response. Pure WPA3 connections show WPA2 too, and I can't connect, not even with nmcli, so I guess that's something wrong with my setup. WPA2/WPA3 connections work fine.

**Comment by firecat53** [comment]
I realized I actually could create a WPA3 network with my Unifi AP. Tested and I'm able to both connect to and view WPA3 connections. Let me know if the latest changes still work for you, and I'll merge this to main. Thanks!

**Comment by saghya** [comment]
Works like a charm!
