### ISSUE TITLE
Remove rofi number of rows option

### ISSUE THREAD

**Issue by vanhtuan0409** [firecat53/networkmanager-dmenu#121]
https://github.com/firecat53/networkmanager-dmenu/blob/main/networkmanager_dmenu#L98

Currently, networkmanager-dmenu forces rofi to display all networks in the window popup. In case of too many wifi network available, the popup will overflow screen size and I cannot see some network available

Is it possible to remove rofi `-l` option here?

**Comment by firecat53** [comment]
Good catch, thanks! Fixed.
