### ISSUE TITLE
allow controlling bluetooth with a bluez

### ISSUE THREAD

**Issue by craftyguy** [firecat53/networkmanager-dmenu#127]
bluez can generally be used by non-root users without having to add udev rules / access /dev/rfkill directly. there's a dbus API but I don't see any obvious methods for managing BT adapter power... but using `bluetoothctl` directly (e.g. `bluetoothctl power on/off` for the default adapter) would be a simple option too I think.

**Comment by firecat53** [comment]
I added bluetoothctl as an option for controlling bluetooth to the `develop` branch. Let me know if it works for you. Try to break it if you can :) Thanks!
