### ISSUE TITLE
Unable to run application - problem with NM.Client

### ISSUE THREAD

**Issue by kamilkrz** [firecat53/networkmanager-dmenu#129]
```Traceback (most recent call last):
  File "/home/kamkrz/bin/networkmanager_dmenu", line 1015, in <module>
    main()
  File "/home/kamkrz/bin/networkmanager_dmenu", line 1007, in main
    CLIENT = NM.Client.new(None)
             ^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-io-error-quark: Could not connect: No such file or directory (1)```

I am a bit lost what file I am missing. 

This worked before but after some updates on my system it stopped.

Thanks in advance

**Comment by firecat53** [comment]
From the README:

   4. Python gobject (PyGObject, python-gobject, etc.)
   5. (Debian/Ubuntu based distros) libnm0 (libnm-util-dev on older distributions)
      and gir1.2-nm-1.0 (you have to explicitly install the latter on Debian Sid)

Beyond that, it's hard to say without knowing your distro.

**Comment by firecat53** [comment]
Did you ever solve this or can you give me some more information? Thanks!

**Comment by firecat53** [comment]
Closing for now. Feel free to reopen with more information. Thanks!
