### ISSUE TITLE
GObject errors when ran

### ISSUE THREAD

**Issue by bubbybubbles** [firecat53/networkmanager-dmenu#135]
I have been trying to get this app to work however whenever I run the script I get the following error 
```
(process:21312): GLib-GObject-CRITICAL **: 09:58:19.288: g_object_get_qdata: assertion 'G_IS_OBJECT (object)' failed

(process:21312): GLib-GObject-CRITICAL **: 09:58:19.288: g_object_set_qdata_full: assertion 'G_IS_OBJECT (object)' failed

(process:21312): GLib-GObject-CRITICAL **: 09:58:19.288: g_object_set_qdata_full: assertion 'G_IS_OBJECT (object)' failed

(process:21312): GLib-GObject-CRITICAL **: 09:58:19.289: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

(process:21312): GLib-GObject-CRITICAL **: 09:58:19.289: g_object_get_qdata: assertion 'G_IS_OBJECT (object)' failed

(process:21312): GLib-GObject-CRITICAL **: 09:58:19.289: g_object_set_qdata_full: assertion 'G_IS_OBJECT (object)' failed

(process:21312): GLib-GObject-CRITICAL **: 09:58:19.289: g_object_set_qdata_full: assertion 'G_IS_OBJECT (object)' failed

(process:21312): GLib-GObject-CRITICAL **: 09:58:19.289: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```
I am running arch with sway as my wm I installed the python-gobject package and tried both running the script from the repo and installing from the AUR package.

**Comment by firecat53** [comment]
I did a minimal Arch install in a VM with sway, wmenu, foot, networkmanager, git and python-gobject. I cloned the repo from Github but I didn't see any of those errors and networkmanager_dmenu worked fine running from the repo `./networkmanager_dmenu` (after setting `dmenu_command = wmenu` in config.ini). Is your launcher wayland-compatible and set in the config file?

**Comment by bubbybubbles** [comment]
I am using fuzzel however your comment about the config file made me go back and check mine.  Turns out there was a stray ` character that was there when pasting from the example.  Sorry for the trouble and thank you for looking into the issue.
