### ISSUE TITLE
Connection editor does not open if gnome is installed, but user is not using gnome

### ISSUE THREAD

**Issue by lugeha** [firecat53/networkmanager-dmenu#137]
https://github.com/firecat53/networkmanager-dmenu/blob/0bd2f11fdc6c028bada5c54e67051124631278fe/networkmanager_dmenu#L749

If you have gnome installed and the user is not in a gnome session, the connection editor will not launch as it tries to use gnome-control-center.

#136 allows you to select which gui editor to use.

**Comment by firecat53** [comment]
Fixed by #136.
