### ISSUE TITLE
Arch AUR package: dependency for python-gobject missing

### ISSUE THREAD

**Issue by gebeer** [firecat53/networkmanager-dmenu#139]
Thank you for this great script!

Would be nice if python-gobject could be included as a dependency in the AUR package. 

It is mentioned as dependency in the README. But reading all through the manual is not everyones strength :-)

**Comment by firecat53** [comment]
From the PKGBUILD:
```
license=('MIT')
depends=('python' 'networkmanager' 'python-gobject')
makedepends=('git')
```

I think it's already there. Are you seeing something different?

**Comment by gebeer** [comment]
> From the PKGBUILD:
> 
> ```
> license=('MIT')
> depends=('python' 'networkmanager' 'python-gobject')
> makedepends=('git')
> ```
> 
> I think it's already there. Are you seeing something different?

I'm sorry. It didn't get installed as dependency using paru and I didn't even check the PKGBUILD before complaining here. Sorry again for the noise.
