### ISSUE TITLE
[Feature Request] Is it possible to add emoji to options presented in rofi menu?

### ISSUE THREAD

**Issue by LoneBrokeBoy** [firecat53/networkmanager-dmenu#142]
It would make it more visually appealing and user friendly if the options had emojis in them. 
Right now, it is == that indicates that connection is on. 
It'd be better there was option to use emojis instead.

**Comment by firecat53** [comment]
Check the example config options....you can set your own:

```
# wifi_chars = <string of 4 unicode characters representing 1-4 bars strength>
# wifi_chars = ▂▄▆█
# wifi_icons = <characters representing signal strength as an icon>
# wifi_icons = 󰤯󰤟󰤢󰤥󰤨
```

**Comment by firecat53** [comment]
Does that option solve your request?

**Comment by LoneBrokeBoy** [comment]
Ohhh I'm sorry. I didn't notice that option on config. Sorry for the trouble and thanks for replying.

I've tried
`active_chars = 󰛳`
but the emoji is too close to name. so I tried `active_chars = "󰛳   "` but that didn't work and it included the quotation mark. Is there anyway to add padding around the active_chars? and Is there inactive_chars?
