### ISSUE TITLE
Fails with UnboundLocalError when `list_saved=True` is set

### ISSUE THREAD

**Issue by winkelnp** [firecat53/networkmanager-dmenu#143]
Description:
On run `networkmanager-dmenu` fails with an UnboundLocalError as it cannot find the variable `hotspot` in `_create_vpngsm_actions`.

I tested this with each option and the only one (that I use) that it happened with was `list_saved=True`

Error message:
```
Traceback (most recent call last):
  File "/usr/bin/networkmanager_dmenu", line 1071, in <module>
    main()
  File "/usr/bin/networkmanager_dmenu", line 1067, in main
    run()
  File "/usr/bin/networkmanager_dmenu", line 1047, in run
    saved_actions = create_saved_actions(saved_cons)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/networkmanager_dmenu", line 528, in create_saved_actions
    return _create_vpngsm_actions(saved, [], "SAVED")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/networkmanager_dmenu", line 542, in _create_vpngsm_actions
    action_name = f"{con.get_id()}{hotspot}:{label}"
                                   ^^^^^^^
UnboundLocalError: cannot access local variable 'hotspot' where it is not associated with a value
```

This is on the AUR Package

**Comment by firecat53** [comment]
I added a bugfix to the `develop` branch. If you could test that and report back I can push the fix to `main`. Thanks!

**Comment by winkelnp** [comment]
Confusingly I now can't seem to replicate the error with or without the fix...
I also can't see what else might have changed, as far as I can tell nothing else has changed.
