### ISSUE TITLE
does not work with multiple wireless cards

### ISSUE THREAD

**Issue by legrostdg** [firecat53/networkmanager-dmenu#31]
I set the same network name on two different wireless cards. After that, networkmanager-dmenu refuses to start:

    $ ./networkmanager_dmenu 
    Traceback (most recent call last):
      File "./networkmanager_dmenu", line 539, in <module>
        run()
      File "./networkmanager_dmenu", line 522, in run
        ap_actions = create_ap_actions(*create_ap_list(adapter))
      File "./networkmanager_dmenu", line 504, in create_ap_list
        raise ValueError("Multiple connection profiles match"
    ValueError: Multiple connection profiles match the wireless AP

**Comment by firecat53** [comment]
Are both adapters available (like wlan0 and wlan1 both being visible)? 

If so, is it first prompting you to choose the adapter?

If so, does it crash right after choosing the adapter?

Try the 'develop' branch. I added a fix which hopefully will fix the problem. I can't really troubleshoot it very well without 2 wifi cards though!

**Comment by stkevintan** [comment]
same issue

**Comment by legrostdg** [comment]
I don't have my second adapter right now, so I can't test your fix. I'll try that on Monday.

The crash happens before choosing the adapter: the dmenu window doesn't open at all.

The same network was set before on the two adapters, with networkmanager-dmenu. The adapter selection worked perfectly there.

If the adapter is not plugged, everything seems to work well again.

**Comment by legrostdg** [comment]
maybe @stkevintan can try the fix?

**Comment by ainola** [comment]
I recently moved from one laptop to another and hit this. It would appear that merely having the same WAP associated with multiple cards triggers this bug regardless of hardware presence.

**Comment by ainola** [comment]
I can confirm that the develop branch works fine for me.

**Comment by legrostdg** [comment]
It also fixes the issue for me!

**Comment by firecat53** [comment]
Cool, thanks for testing, everyone. I'll push this to master and hopefully it doesn't break something unintended for everyone else :smile:
