### ISSUE TITLE
ValueError: Namespace NM not available

### ISSUE THREAD

**Issue by therockmandolinist** [firecat53/networkmanager-dmenu#32]
I'm getting this error when trying to run the script:
```
Traceback (most recent call last):
  File "./networkmanager_dmenu", line 25, in <module>
    gi.require_version('NM', '1.0')
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace NM not available
```
Unsure what it's about?

**Comment by firecat53** [comment]
What version of python2-gobject (or similar package on your system) is installed?

**Comment by therockmandolinist** [comment]
How would I check that? `gi.version_info` says `(3,20,0)`

**Comment by firecat53** [comment]
Hmm, that doesn't seem too old. I'm only on 3.22 here. How about your libnm-glib package? Mine is 1.6.2.

What distro are you using? Maybe I can fire it up in a VM and see if I can reproduce.

**Comment by therockmandolinist** [comment]
Oh wow, I was missing libnm-glib - perhaps it should be stated in the requirements?

It works with dmenu now, thanks! I'm getting some rofi related issues, I can open a different issue.

**Comment by firecat53** [comment]
What distro are you using? I'll add a note for libnm-glib but I'd like to see on which distros it's required or not by another package (e.g. it's required by networkmanager on Arch).

**Comment by therockmandolinist** [comment]
I'm using elementary OS 0.4 Loki.

**Comment by firecat53** [comment]
So I'm running Elementary 0.4 live CD in a VM, and it has libnm-glib4 installed by default. It also seems to be required by other packages. Any idea why it might not have been installed on your system?

**Comment by therockmandolinist** [comment]
@firecat53 Er, I see that I have libnm-glib4. I think what I installed was libnm-glib-dev. Does that mean I had libnm-glib4 installed already, but for some reason networkmanager_dmenu didn't work until I installed libnm-glib-dev? Can you also get networkmanager_dmenu to work by default in elementary 0.4? It's certainly odd. In any case, I'm rather new to linux and have been enjoying tinkering (aka breaking things only to have to fix them later) so it's entirely possible it was my fault.

**Comment by firecat53** [comment]
Oh, oops. I guess I should have tested that :) Well, I'll get to it in a day or two.

**Comment by firecat53** [comment]
Seems that the debian/ubuntu based distros need libnm-util-dev. Added a README note. Thanks for finding it :smile:
