### ISSUE TITLE
"OSError: [Errno 2] No such file or directory" with rofi -dmenu

### ISSUE THREAD

**Issue by therockmandolinist** [firecat53/networkmanager-dmenu#33]
With `dmenu_command = "rofi -dmenu"` (otherwise I get rofi daemon mode is now removed), I get the following error:

```
Traceback (most recent call last):
  File "./networkmanager_dmenu", line 547, in <module>
    run()
  File "./networkmanager_dmenu", line 542, in run
    gsm_actions, other_actions)
  File "./networkmanager_dmenu", line 306, in get_selection
    env=ENV).communicate(input=inp_bytes)[0].decode(ENC)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
As I said in the other issue, however, it _does_ work with `dmenu_command = "dmenu"`. Any ideas?

**Comment by firecat53** [comment]
Sounds like Rofi may not be in your $PATH.

**Comment by therockmandolinist** [comment]
Not sure if I'm understanding correctly, but i get the same error with `dmenu_command = "/usr/local/bin/rofi -dmenu"` (the full path)

**Comment by firecat53** [comment]
Ok, silly question, but  is rofi actually installed and executable in /usr/local/bin? What's the output of `ls -l /usr/local/bin/rofi` ?

**Comment by therockmandolinist** [comment]
If it's not I may be going crazy, since I'm using rofi for other things as well, and this is the only place it's installed (checked with `locate -r rofi$`).
```shell
$ ls -l /usr/local/bin/rofi
-rwxr-xr-x 1 root root 1049000 Mar 20 19:46 /usr/local/bin/rofi
```

**Comment by firecat53** [comment]
Well, hmmm. That is odd. Ummm...can you post your ~/.config/networkmanager-dmenu/config.ini ?

**Comment by therockmandolinist** [comment]
@firecat53 I believe I may have been being an idiot. I somehow misread the first step of the instructions and was editing the command directly in the .py file, not having a config.ini at all. Of course, my original issue was pretty ambiguous about that.

It's now working without issue as far as I can tell. Sorry for wasting your time, and thanks again!

**Comment by firecat53** [comment]
Heh, no worries! Glad you were able to fix it.
