### ISSUE TITLE
Odd behavior in Kubuntu with i3wm

### ISSUE THREAD

**Issue by therockmandolinist** [firecat53/networkmanager-dmenu#40]
I'm not sure if this has anything to do with the distro, but I _was_ using networkmanager_dmenu on ElementaryOS with i3wm dual booted with macOS, recently changed to single boot Kubuntu with i3wm. I get this behavior where when trying to connect to a password-protected network with networkmanager_dmenu, i'm asked for a passphrase, but when connecting with nm-applet, it sort of just works. Any ideas?

**Comment by firecat53** [comment]
Mmmm...not quite sure what you mean. Can you be more specific please? You should get asked for a passphrase the first time you connect to a secure network...what's the issue?

Run it from the command line...any errors?

**Comment by therockmandolinist** [comment]
Not sure how to clarify. I was already asked for a passphrase the first time connecting to this secure network. (I did this through nm-applet). Now, every time I run `networkmanager_dmenu` and try to connect to this same network, it seems like it doesn't know the password and asks for it again, then doesn't connect to the network anyway. When connecting to the same network with nm-applet, it just connects. There's nothing wrong with actually running `networkmanager_dmenu`, or even connecting to non secure wifi.

**Comment by He-Ro** [comment]
One quick question: Which version of netwockmanager-dmenu are you running? The latest 'master'?

**Comment by firecat53** [comment]
Ok, I understand your question now. Did you setup the PolicyKit permissions per the README? If so, which method are you using?

**Comment by therockmandolinist** [comment]
@He-Ro Using the latest master

@firecat53 I didn't, just because I didn't have to before and it worked fine. Is this a requirement? Forgive my ignorance, but _do I_ want to run the script as $USER instead of as ROOT?

**Comment by firecat53** [comment]
Each distro is different how PolicyKit is setup by default so it's not surprising default behavior could be different when you switch. Yes, you should be running the script as $USER, although using sudo (option 2) is perfectly acceptable. I'm running Arch with i3 and use option 3 which works great.

I'm not 100% positive this is your issue...but about 95% :)

**Comment by therockmandolinist** [comment]
I'm gonna close this - I'm pretty sure my issue was with connecting to the network itself (some CA thing, or how I configured the network or something). I can't exactly pinpoint why at some point it worked with nm-applet and not networkmanager_dmenu since I fiddled with a lot of things (maybe something about "All users may connect to this network" or "Store password for all users" in the network settings?), but at some point I started getting issues with the network regardless, and starting from scratch seemed to fix it on both ends.
