### ISSUE TITLE
Request for release

### ISSUE THREAD

**Issue by concavegit** [firecat53/networkmanager-dmenu#43]
Nothing of major consequence, it would just be nice to have another release for packaging purposes.

**Comment by firecat53** [comment]
Hmm...I actually haven't released any actual versions. This is just a single script with a config file. For which distro are you looking to package? The Arch AUR just pulls the most recent git version.

**Comment by concavegit** [comment]
Woops, I meant a tagged release on this repo so I can write  in a more up-to-date stable gentoo package script.

**Comment by firecat53** [comment]
Ok, released v1.1. I'd forgotten I actually released this as 1.0.0 a few years ago! Thanks for the prompt.
