### ISSUE TITLE
Only connected wifi displayed

### ISSUE THREAD

**Issue by tangxinfa** [firecat53/networkmanager-dmenu#53]
Only the connected WiFI displayed, if i click `nm-applet` to show all WiFIs
first, then run `networkmanager-dmenu`, all WiFIs will show normally.

It looks like must first call `nm_device_wifi_request_scan` and wait for scan result
ready, the scan result will cache in fewer seconds. If you watch `nm-applet` it
show connected WiFi first, one second later it will show other WiFIs, maybe it
did a scan.

For now we can run `nmcli` to do scan before run `networkmanager-dmenu`:

    nmcli d wifi >/dev/null 2>&1 && networkmanager_dmenu

**Comment by firecat53** [comment]
Thanks for the report...I'll take a closer look when I get a chance.

**Comment by firecat53** [comment]
PR #57 added a 'Rescan Wifi Networks' menu option. Hopefully that fixes this issue for you?

**Comment by firecat53** [comment]
Going to close this. Feel free to re-open if you still have issues.
