### ISSUE TITLE
Can't disconnect from a wifi network

### ISSUE THREAD

**Issue by GOKOP** [firecat53/networkmanager-dmenu#58]
When I try to disconnect from the currently connected wifi, I get this:
```Traceback (most recent call last):
  File "./networkmanager_dmenu", line 690, in <module>
    run()
  File "./networkmanager_dmenu", line 686, in run
    sel()
  File "./networkmanager_dmenu", line 246, in __call__
    self.func(*self.args)
  File "./networkmanager_dmenu", line 252, in process_ap
    CLIENT.deactivate_connection_async(nm_ap)
TypeError: Argument 1 does not allow None as a value
```

There are no problems when switching to a different wifi network

**Comment by firecat53** [comment]
Hmm, I can't reproduce that here.

- Does it happen for every network?
- Does it happen every time or just sometimes?
- Are you using the most recent version of networkmanager-dmenu?
- Has it always happened or did it just start recently?
- What version of NetworkManager are you using? (1.16.0 on my machine)

**Comment by GOKOP** [comment]
* I only tested it with two networks because I don't really have access to more right now. Happens for both.
* It happens every time. 
* I'm using version from AUR, but I also tried cloning this repo and it gave me the same result. 
* I've just recently (literally yesterday) started using networkmanager-dmenu so that's all I know. 
* Pacman says my NetworkManager is 1.16.0-1.

Also I'm able do disable connection with nmcli so I don't think it's a NetworkManager problem

**Comment by firecat53** [comment]
Did you enable PolicyKit permissions via one of the methods in [the wiki](https://wiki.archlinux.org/index.php/NetworkManager#Set_up_PolicyKit_permissions)? If so, which method?
Are you using vanilla Arch systemd? Is dbus-daemon running for your user?

**Comment by GOKOP** [comment]
Yes, I'm using vanilla systemd and dbus-daemon is running. I'm in the wheel group. (but I didn't do that specifically to get policykit permissions)

**Comment by firecat53** [comment]
I merged #59 to master. @GOKOP, give it a try and see if it fixes your issue. Probably should delete your connection and re-add it.

**Comment by GOKOP** [comment]
Nothing changed unfortunately.  
Sorry it took so long but the only computer on which I can test it wasn't quite operating and I was too lazy to deal with it

**Comment by firecat53** [comment]
Going to check once more to make sure you deleted the connection and verified that it does not exist in /etc/NetworkManager/system-connections. After you
re-add the connection, the first part of your <ssid>.nmconnection file there should look something like:

    [connection]
    id=<your ssid>
    uuid=ff6bd923-884l-ff62-ffff-ff6bffffffff
    type=wifi
    permissions=
    timestamp=1558560202

    [wifi]
    mac-address=D9:99:99:99:7A:8C
    mac-address-blacklist=
    mode=infrastructure
    seen-bssids=99:99:99:99:99:99;
    ssid=<your ssid>

I was able to replicate your problem when I ended up with multiple *.nmconnection files for one ssid and I didn't have the `mac-address=xx:xx....` in the file.

**Comment by GOKOP** [comment]
Oh, ok. After deleting the connection everything works perfectly. Thanks!

**Comment by mb720** [comment]
Hi and thanks a lot for networkmanager-dmenu!

I just ran into this trying out networkmanager-dmenu for the first time: When I hit enter while the currently active network is selected in rofi, I get this stack trace:

    Traceback (most recent call last):
      File "/usr/bin/networkmanager_dmenu", line 703, in <module>
        run()
      File "/usr/bin/networkmanager_dmenu", line 699, in run
        sel()
      File "/usr/bin/networkmanager_dmenu", line 238, in __call__
        self.func(*self.args)
      File "/usr/bin/networkmanager_dmenu", line 244, in process_ap
        CLIENT.deactivate_connection_async(nm_ap)
    TypeError: Argument 1 does not allow None as a value

My user is member of the group `wheel`.

I looked into `/etc/NetworkManager/system-connections/` and didn't find any duplicates there.

These are the changes I made to `~/.config/networkmanager-dmenu/config.ini`:

    rofi_highlight = True
    terminal = termite
    dmenu_command = /usr/bin/rofi -l 10


Here is the last part of `networkmanager_dmenu --help`:

  Monitor layout:
                ID: 0
              name: XWAYLAND0
          position: 0,0
              size: 1366,768
              size: 280mm,160mm  dpi: 124,122


  Detected modi:
          * window
          * windowcd
          * run
          * ssh
          * drun
          * combi
          * keys

  Compile time options:
          * window  enabled
          * drun    enabled
          * gcov    disabled
          * asan    disabled

  For more information see: man rofi
                  Version: 1.5.4
                Bugreports: https://github.com/davatorium/rofi/
                  Support: https://reddit.com/r/qtools/
                            #rofi @ freenode.net
        Configuration file: /home/mb/.config/rofi/config'


Thanks for looking into this!
