### ISSUE TITLE
How to update WiFI list automatically

### ISSUE THREAD

**Issue by coiby** [firecat53/networkmanager-dmenu#67]
Hi,

When networkmanager-dmenu is lanched the second or the third time, the WiFI list is stale. I've to toggle WiFI off/on in order to get latest SSIDs. Is there a way to configure networkmanager-dmenu so it'll have the latest SSID list each time it's launched.

Thank you!

**Comment by firecat53** [comment]
I added the `Rescan Wifi Networks` option a while ago as an on-demand trigger. The problem with doing that each time the program is called is purely a speed issue. The lag on opening would be noticeable and that seems like not the best user experience. You shouldn't need to toggle wifi on-off. Just hit the `Rescan` option and wait for several seconds before opening it again.

**Comment by firecat53** [comment]
@coiby Does this answer your question?

**Comment by coiby** [comment]
Yes, thank you for adding "Rescan Wifi Networks". I needn't to toggle on and off wifi manually now. Btw, I noticed nm-applet (network-manager-applet) doesn't have the speed issue. Is it because it has a running daemon process that rescans wifi networks automatially?

**Comment by firecat53** [comment]
I would guess so. Not 100% sure without looking at their code. Seems like this is at least working for you now so I'll go ahead and close. Thanks for your interest!
