### ISSUE TITLE
How to replace the * with bars

### ISSUE THREAD

**Issue by eyadsibai** [firecat53/networkmanager-dmenu#70]
Thank you for the cool tool!

I was wondering how to replace the *** with bars instead that represent the strength of the signal?

**Comment by firecat53** [comment]
That will take a PR. The `NM.utils_wifi_strength_bars` function that's provided by NetworkManager returns 0-4 asterisks. The comment in the docs says that they used to try to create bars, but there were too many terminal types to easily guess Unicode abilities. 

The asterisks could be converted locally to Unicode bars fairly easily after the `NM.utils_wifi_strength_bars` call in the `create_ap_actions` function. 

Thanks for your interest!

**Comment by firecat53** [comment]
In config.ini set:

    [dmenu]
    wifi_chars = ▂▄▆█

Hopefully that works for you!

**Comment by eyadsibai** [comment]
thanks!!
