### ISSUE TITLE
would like to use wofi instead of rofi for pure wayland

### ISSUE THREAD

**Issue by biwhite** [firecat53/networkmanager-dmenu#71]
wofi has slightly different arguments to rofi, so unfortunately not just a drop in replacement

**Comment by firecat53** [comment]
Sorry for the delay in responding! I haven't experimented with Wayland at all yet. I did a quick browse of the wofi repo, but didn't have time to dig into the docs. Are you able to figure out which command line options would need alteration in order to make it work?

**Comment by avrelaun** [comment]
`wofi -d` seems to be the dmenu mode for wofi, it should be compatible

**Comment by avrelaun** [comment]
to make it compatible, add this to the file `.config/networkmanager-dmenu/config.ini`:
```
[dmenu]
dmenu_command = /usr/bin/wofi -d
```

**Comment by biwhite** [comment]
Seems the 'fn' option messes it up.  works with -d, without the 'fn' option set.

**Comment by firecat53** [comment]
@l4l submitted a PR (#83) to start adding support for wofi. Anyone here care to address the best way to handle the lack of support for the `fn` flag? Maybe not use it and address in the documentation?

**Comment by chron-isch** [comment]
I don't really mind the font, but I would really like to have pango markup support.

**Comment by firecat53** [comment]
@chron-isch I doubt pango markup is something I will add. In my opinion that adds a pretty substantial complexity for a minimalist tool that is rarely visible.

**Comment by chron-isch** [comment]
@firecat53 I think you misunderstood my comment, i wasn't asking for generic pango markup support, just replacing the rofi highlighting code with a little bit of pango markup to get highlighting of active network connections to work in wofi.

**Comment by firecat53** [comment]
@chron-isch :  Ah, I see. I'd be happy to review a PR if you'd care to take a stab at it.

**Comment by markstos** [comment]
There's also a fork of `rofi` that supports Wayland now:

https://github.com/lbonn/rofi#wayland-support

Not everything works though-- notably the window switching mode is not supported. 

However, there is a `dmenu` based solution for window switching on Sway that works to see and switch to XWayland windows as well, using this `bash` script:

```
  swaymsg -t get_tree |
         jq -r '.nodes[].nodes[] | if .nodes then [recurse(.nodes[])] else [] end + .floating_nodes | .[] |  se‐
       lect(.nodes==[]) | ((.id | tostring) + " " + .name)' |
         wofi --show dmenu | {
           read -r id name
           swaymsg "[con_id=$id]" focus
       }
```
However, since rofi supports custom modes that supply their own scripts, perhaps this approach could be used as the basis to implement a window switching mode for Sway, using the Wayland fork of `rofi`.

**Comment by mordax777** [comment]
Where to find the PR for the Wofi implementation?

**Comment by markstos** [comment]
@mordax777 The comment above describes how to make it work for `wofi`: 

https://github.com/firecat53/networkmanager-dmenu/issues/71#issuecomment-610823022

**Comment by p00f** [comment]
@firecat53 You already handle rofi with a special case, can you add one for wofi too:
```python
        if "wofi" in dmenu_command:
            lines = "--dmenu --insenstive --lines"
```
