### ISSUE TITLE
Can't launch script

### ISSUE THREAD

**Issue by waddlefluf** [firecat53/networkmanager-dmenu#81]
When I try to the run the script on debian stable I get the following error:
```
Traceback (most recent call last):
  File "/home/fluf/.scripts/networkmanager-dmenu", line 707, in <module>
    run()
  File "/home/fluf/.scripts/networkmanager-dmenu", line 683, in run
    wgs = [i for i in CONNS if i.is_type(NM.SETTING_WIREGUARD_SETTING_NAME)]
  File "/home/fluf/.scripts/networkmanager-dmenu", line 683, in <listcomp>
    wgs = [i for i in CONNS if i.is_type(NM.SETTING_WIREGUARD_SETTING_NAME)]
  File "/usr/lib/python3/dist-packages/gi/module.py", line 132, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.NM' object has no attribute 'SETTING_WIREGUARD_SETTING_NAME'
```
Seems like it might be a problem with the gi library in python, but I'm not sure.

**Comment by waddlefluf** [comment]
Sorry for not specifying these earlier. Python's version is 3.7.3 and pythonGobject is on 3.30.4-1

**Comment by firecat53** [comment]
Ok, what distro are you using? 

I may have to put it a check to see if Wireguard is supported by older versions of python-gobject.

**Comment by waddlefluf** [comment]
I'm on Debian 10 Stable (buster).

**Comment by firecat53** [comment]
This should be fixed with the latest master. Please let me know if it works for you.

**Comment by waddlefluf** [comment]
It is working for me, thank you.

**Comment by firecat53** [comment]
Glad it's working! Thanks for your interest.
