### ISSUE TITLE
Deprecation issues

### ISSUE THREAD

**Issue by GoDzM4TT3O** [firecat53/networkmanager-dmenu#82]
When trying to run "Delete a connection" and/or "Rescan Wi-Fi networks", I get the following errors, respectively:

```
/usr/bin/networkmanager_dmenu:177: DeprecationWarning: NM.DeviceWifi.request_scan is deprecated
    dev.request_scan()
```

```
/usr/bin/networkmanager_dmenu:238: DeprecationWarning: NM.RemoteConnection.delete is deprecated
    self.func()
```

This might be an issue for other commands too

EDIT: "Enable/Disable Wifi/Networking" (Wifi = line 466, Networking = line 457) works, but still gives a deprecation warning:

```
/usr/bin/networkmanager_dmenu:466: DeprecationWarning: NM.Client.wireless_set_enabled is deprecated
    CLIENT.wireless_set_enabled(enable)
```

**Comment by firecat53** [comment]
Thanks for the report. Taking a look at all the commands now...

**Comment by firecat53** [comment]
Fixed the rescan and delete connection deprecations. Still looking at the wifi and networking toggles. Having a hard time understanding how to make those work. 

[Here](https://lazka.github.io/pgi-docs/index.html#NM-1.0/classes/Client.html%23NM.Client.dbus_call) is the documentation for the new call to be made in place of `networking_set_enabled` and/or `wireless_set_enabled`. Here's what I've tried that doesn't work:

    $ ipython
    import gi
    gi.require_version('NM', '1.0')
    from gi.repository import GLib, NM
    CLIENT=NM.Client.new()
    toggle = GLib.Variant.new_tuple(GLib.Variant.new_boolean(False))
    CLIENT.dbus_set_property(NM.DBUS_PATH, NM.DBUS_INTERFACE, "WirelessEnabled", toggle, -1, None, None, None)

Nothing happens, no error messages. Also tried:

    toggle = GLib.Variant.new_tuple(GLib.Variant.new_string("WirelessEnabled"), GLib.Variant.new_boolean(False))
    CLIENT.dbus_call(NM.DBUS_PATH, NM.DBUS_INTERFACE, "Set", toggle, None, -1, None, None, None)

Still nothing and no errors. I can't seem to locate any other documentation or examples using these calls. Open to ideas!

**Comment by firecat53** [comment]
Figured it out! There was a documentation error for `dbus_get_property`. Thanks for the report.
