### ISSUE TITLE
Unable to activate VPN connection

### ISSUE THREAD

**Issue by vanhtuan0409** [firecat53/networkmanager-dmenu#85]
Hi, recently I did some update to system and networkmanager-dmenu break without me knowing why

Try to invoke networkmanager-dmenu from CLI show some error as

```
(process:37988): GLib-GObject-CRITICAL **: 23:25:22.062: g_object_get_qdata: assertion 'G_IS_OBJECT (object)' failed

(process:37988): GLib-GObject-CRITICAL **: 23:25:22.062: g_object_set_qdata_full: assertion 'G_IS_OBJECT (object)' failed

(process:37988): GLib-GObject-CRITICAL **: 23:25:22.062: g_object_set_qdata_full: assertion 'G_IS_OBJECT (object)' failed

(process:37988): GLib-GObject-CRITICAL **: 23:25:22.062: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

Networkmanager-dmenu installed from master via AUR
python-gobject version is 3.36.1-1, installed from manjaro repository

Hope you can give me some clues. Tks in advance

**Comment by vanhtuan0409** [comment]
Figure out that networkmanager_dmenu require nm-applet to run in the background 
close ticket because it is working for me

**Comment by firecat53** [comment]
Netowrkmanager_dmenu does not require nm-applet to be running. Try stopping the applet and running the script again. When you installed the applet it may have installed a missing dependency.
