### ISSUE TITLE
Well, trivial, but extrememly important for adoption by less technical people like me :)

### ISSUE THREAD

**Issue by unixbhaskar** [firecat53/networkmanager-dmenu#86]
Please include screenshots or asciinema videos for the layman. Please take note from the Wireguard install/quick start guide for how to do that. Also, please write down the exact step by step procedure in your GitHub front page. 

So, the reason being, if you are not targeted a specific user group and make it available for everyone, make sure you expose enough details in clear form.

It is a free suggestion, you are free to ignore.

**Comment by firecat53** [comment]
Thanks for the idea. However, my tools are generally targeted to more advanced users that are capable of configuring minimal window managers like i3 and dwm. I always try to write thorough documentation, but I'm not too keen on creating videos (personal preference). If you have specific ideas on improving the documentation, I'd certainly be open to ideas. Thanks for your interest!
