### ISSUE TITLE
Deactivating connection raises TypeError

### ISSUE THREAD

**Issue by The-Compiler** [firecat53/networkmanager-dmenu#92]
When I want to deactivate an existing connection, I get:

```
Traceback (most recent call last):
  File "networkmanager_dmenu", line 814, in <module>
    run()
  File "networkmanager_dmenu", line 810, in run
    sel()
  File "networkmanager_dmenu", line 262, in __call__
    self.func(*self.args)
  File "networkmanager_dmenu", line 268, in process_ap
    CLIENT.deactivate_connection_async(nm_ap, None, deactivate_cb, nm_ap)
TypeError: Argument 1 does not allow None as a value
```

**Comment by firecat53** [comment]
Does this happen for all connections or just a particular one? I don't see that for the Wifi or VPN connections that I use.

**Comment by The-Compiler** [comment]
Ah, this might actually be the same underlying cause as #91 (I'm trying with the `eduroam` connection from there):

- `create_ap_list` filters out the active connection from `conns_cur` because of the MAC address filtering
- `active_ap_con` is `None`
- Thus, `active_connection` in `create_ap_actions` is `None` (but `is_active` is `True`)
- Thus, `process_ap` gets called with `nm_ap` being `None`
- Thus, `CLIENT.deactivate_connection_async` gets called with `None` as first argument and raises.

**Comment by firecat53** [comment]
Aha! The method you wrote for #93 works perfectly to fix this issue as well when applied to creating the list of current connections in `create_ap_list()`. Let me know if the `devel` branch works for you now.

**Comment by firecat53** [comment]
I went ahead and closed this. Reopen or let me know if it doesn't work for you. Thanks!
