### ISSUE TITLE
Script not working with patched dmenu

### ISSUE THREAD

**Issue by mstanciu552** [firecat53/networkmanager-dmenu#95]
I recently switches to a tiling window manager(**Awesome**) and I started getting into **dmenu**.

I love this script because it's very easy to use and it has a lot of functionality, but since I **patched my dmenu** installation it stopped working. 
![image](https://user-images.githubusercontent.com/34579048/126626348-cde35451-3a9a-40e5-8d06-6db78e06bc34.png)
This is what it gives back....Can anyone help with this?

**Comment by firecat53** [comment]
It looks like the patch you applied changed the command line options. There are a couple of options applied by NetworkManager when it calls dmenu. I'd check the source for both and see what options your patch changed that are applicable.

**Comment by firecat53** [comment]
Did you get this solved?

**Comment by mstanciu552** [comment]
Oh yeah I removed the case insensitive patch.
