### ISSUE TITLE
G_IS_OBJECT failed warning

### ISSUE THREAD

**Issue by RaZ0rr-Two** [firecat53/networkmanager-dmenu#97]
I am running mx linux 19.4 based on debian 10 (buster). I am getting the following error when running the networkmanager-dmenu script. I have installed all the mentioned dependencies

```
(process:19628): GLib-GObject-CRITICAL **: 22:03:00.909: g_object_get_qdata: assertion 'G_IS_OBJECT (object)' failed

(process:19628): GLib-GObject-CRITICAL **: 22:03:00.910: g_object_set_qdata_full: assertion 'G_IS_OBJECT (object)' failed

(process:19628): GLib-GObject-CRITICAL **: 22:03:00.910: g_object_set_qdata_full: assertion 'G_IS_OBJECT (object)' failed

(process:19628): GLib-GObject-CRITICAL **: 22:03:00.910: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

**Comment by RaZ0rr-Two** [comment]
I read somewhere that those gtk warnings are not serios and can be ignored ( or & , /dev/null ). But I'm more concerned about the reason my nm_dmenu doesn't work when I uncomment out `list_saved` option.

**Comment by firecat53** [comment]
Did you ever get this working?

**Comment by RaZ0rr-Two** [comment]
Oops sorry for not closing. It does work without an issue. The errors are still there. But these errors also show when I open any gtk app from terminal like thunar, firefox. Anyway, it is working for me
