### ISSUE TITLE
Desktop Entry

### ISSUE THREAD

**Issue by joaopauloalbq** [firecat53/networkmanager-dmenu#98]
![network](https://user-images.githubusercontent.com/9905202/142654256-8ea1ede1-00ee-4552-8e99-f091562a390f.png)

Desktop entry has no icon and application name is weird even containing a '_'

**Comment by firecat53** [comment]
Do have a proposal for an icon and a 'proper' name? I have no use for the .desktop file so I genuinely don't know what other people would like to see!

**Comment by joaopauloalbq** [comment]
![Screenshot_20211119_171145](https://user-images.githubusercontent.com/9905202/142688741-dafb578e-b945-45ce-8119-48a523544e79.png)
![Screenshot_20211119_171207](https://user-images.githubusercontent.com/9905202/142688743-220ad989-7201-4081-9974-2bca76a2fa6d.png)


`nm-device-wireless` icon looks good to me, `cs-network` is also a option 🤔

Regarding the name I would change it to just _Network Manager_ or _Connection Manager_



Thanks for the amazing work :)

**Comment by firecat53** [comment]
I used the nm-device-wireless icon even though it looks completely different on
my system. At least it show something :)
