### ISSUE TITLE
[Feature Request] Include screenshot or screen recording

### ISSUE THREAD

**Issue by ethagnawl** [firecat53/networkmanager-dmenu#99]
I think it'd be helpful for people coming across this project to see it in action. I'd like to propose including either a static screenshot or a screen recording which demonstrates baseline functionality.

If you'd consider a PR, I'd be willing to put one together.

Thanks for such a useful utility!

**Comment by firecat53** [comment]
Yeah, that's a good idea. I'll give it a go, because I have a few other projects
that could probably use that too. Thanks!

**Comment by firecat53** [comment]
Is the screen recording I added good enough? That was more challenging to get
right than I thought it would be! Open to suggestions for improvements.

**Comment by ethagnawl** [comment]
Yeah, that's great. Thanks!

Also, I happened to be making a screen recording myself (first in months) when I saw the notification about this PR pop up. What are the chances of that?
